### ISSUE TITLE
No module named 'lxml'

### ISSUE THREAD

**Issue by dyskette** [flathub/org.gnome.World.Secrets#8]
Halp, I just got a notification about an update and it's broken now. 😱

```
flatpak run org.gnome.World.Secrets 
Traceback (most recent call last):
  File "/app/bin/secrets", line 66, in <module>
    main()
  File "/app/bin/secrets", line 57, in main
    from gsecrets.application import Application
  File "/app/lib/python3.9/site-packages/gsecrets/application.py", line 11, in <module>
    from gsecrets.widgets.window import Window
  File "/app/lib/python3.9/site-packages/gsecrets/widgets/window.py", line 12, in <module>
    from gsecrets.database_manager import DatabaseManager
  File "/app/lib/python3.9/site-packages/gsecrets/database_manager.py", line 10, in <module>
    from pykeepass import PyKeePass
  File "/app/lib/python3.9/site-packages/pykeepass/__init__.py", line 2, in <module>
    from .pykeepass import PyKeePass, create_database
  File "/app/lib/python3.9/site-packages/pykeepass/pykeepass.py", line 16, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

**Comment by A6GibKm** [comment]
Thanks, this is weird, lxml is in the runtime.... Ill fix it asap

**Comment by dyskette** [comment]
It works now. Thanks.
